# Utilities for synthesizing digital video timings and presenting a framebuffer.
#
# Copyright (c) 2024 Seb Holzapfel <me@sebholzapfel.com>
#
# SPDX-License-Identifier: CERN-OHL-S-2.0

import colorsys
import os

from amaranth              import *
from amaranth.build        import *
from amaranth.lib          import wiring, data, stream
from amaranth.lib.wiring   import In, Out
from amaranth.lib.fifo     import AsyncFIFOBuffered
from amaranth.lib.cdc      import FFSynchronizer
from amaranth.utils        import exact_log2
from amaranth.lib.memory   import Memory

from amaranth_soc          import wishbone

from dataclasses           import dataclass

from tiliqua               import sim

@dataclass
class DVIPLL:
    pixel_clk_mhz: float
    clki_div:      int
    clkop_div:     int
    clkop_cphase:  int
    clkos_div:     int
    clkos_cphase:  int
    clkos2_div:    int
    clkos2_cphase: int
    clkos2_cphase: int
    clkfb_div:     int

@dataclass
class DVITimings:
    h_active:      int
    h_sync_start:  int
    h_sync_end:    int
    h_total:       int
    h_sync_invert: bool
    v_active:      int
    v_sync_start:  int
    v_sync_end:    int
    v_total:       int
    v_sync_invert: bool
    refresh_rate:  float
    pll:           DVIPLL

DVI_TIMINGS = {
    # CVT 640x480p59.94
    # Every DVI-compatible monitor should support this, according to the standard.
    # These numbers correspond directly to `xrandr --verbose`, if you're reading an EDID.
    "640x480p59.94": DVITimings(
        h_active      = 640,
        h_sync_start  = 656,
        h_sync_end    = 752,
        h_total       = 800,
        h_sync_invert = True,
        v_active      = 480,
        v_sync_start  = 490,
        v_sync_end    = 492,
        v_total       = 525,
        v_sync_invert = True,
        refresh_rate  = 59.94,
        # DVIPLL() instances are generated by looking at the results of incantations like:
        # $ ecppll -i 48 --clkout0 371.25 --highres --reset -f pll60.v
        # where clkout0 is 5x the pixel clock. clkos2_div set by inspection to clkos_div*5.
        pll = DVIPLL(
            pixel_clk_mhz = 25.175,
            clki_div      = 9,
            clkop_div     = 59,
            clkop_cphase  = 9,
            clkos_div     = 5,
            clkos_cphase  = 0,
            clkos2_div    = 25,
            clkos2_cphase = 0,
            clkfb_div     = 2
        )
    ),

    # DMT 800x600p60
    "800x600p60": DVITimings(
        h_active      = 800,
        h_sync_start  = 840,
        h_sync_end    = 968,
        h_total       = 1056,
        h_sync_invert = False,
        v_active      = 600,
        v_sync_start  = 601,
        v_sync_end    = 605,
        v_total       = 628,
        v_sync_invert = False,
        refresh_rate  = 60.317,
        pll = DVIPLL(
            pixel_clk_mhz = 40,
            clki_div      = 2,
            clkop_div     = 25,
            clkop_cphase  = 9,
            clkos_div     = 3,
            clkos_cphase  = 0,
            clkos2_div    = 15,
            clkos2_cphase = 0,
            clkfb_div     = 1
        )
    ),

    # DMT 1280x720p60
    "1280x720p60": DVITimings(
        h_active      = 1280,
        h_sync_start  = 1390,
        h_sync_end    = 1430,
        h_total       = 1650,
        h_sync_invert = False,
        v_active      = 720,
        v_sync_start  = 725,
        v_sync_end    = 730,
        v_total       = 750,
        v_sync_invert = False,
        refresh_rate  = 60.00,
        pll = DVIPLL(
            pixel_clk_mhz = 74.25,
            clki_div      = 15,
            clkop_div     = 58,
            clkop_cphase  = 9,
            clkos_div     = 2,
            clkos_cphase  = 0,
            clkos2_div    = 10,
            clkos2_cphase = 0,
            clkfb_div     = 4
        )
    ),

    "1920x1080p30": DVITimings(
        h_active      = 1920,
        h_sync_start  = 2008,
        h_sync_end    = 2052,
        h_total       = 2200,
        h_sync_invert = False,
        v_active      = 1080,
        v_sync_start  = 1084,
        v_sync_end    = 1089,
        v_total       = 1125,
        v_sync_invert = False,
        refresh_rate  = 30.00,
        pll = DVIPLL(
            pixel_clk_mhz = 74.25,
            clki_div      = 15,
            clkop_div     = 58,
            clkop_cphase  = 9,
            clkos_div     = 2,
            clkos_cphase  = 0,
            clkos2_div    = 10,
            clkos2_cphase = 0,
            clkfb_div     = 4
        )
    ),

    # BEGIN ODDBALL TIMINGS

    # A round AliExpress display
    "720x720p60": DVITimings(
        h_active      = 720,
        h_sync_start  = 760,
        h_sync_end    = 780,
        h_total       = 820,
        h_sync_invert = False,
        v_active      = 720,
        v_sync_start  = 744,
        v_sync_end    = 748,
        v_total       = 760,
        v_sync_invert = False,
        refresh_rate  = 60.0,
        pll = DVIPLL(
            pixel_clk_mhz = 74.25,
            clki_div      = 12,
            clkop_div     = 17,
            clkop_cphase  = 9,
            clkos_div     = 4,
            clkos_cphase  = 0,
            clkos2_div    = 20,
            clkos2_cphase = 0,
            clkfb_div     = 11
        )
    ),
}

class DVITimingGenerator(wiring.Component):

    """
    State machine to generate pixel position and hsync/vsync/de signals.
    Designed to run in the DVI pixel clock domain.

    Warn: Sync inversion is NOT handled here in case the logic of this block drives
    other signals (e.g. framebuffer vsync). Inversion is handled just before the PHY.
    """

    def __init__(self, timings: DVITimings, coord_width=16):
        self.timings = timings

        # coordinates at which each frame starts
        self.h_reset = timings.h_active - timings.h_total
        self.v_reset = timings.v_active - timings.v_total

        # coordinates at which sync starts / ends
        self.hs_start = timings.h_sync_start - timings.h_total
        self.vs_start = timings.v_sync_start - timings.v_total
        self.hs_end   = timings.h_sync_end   - timings.h_total
        self.vs_end   = timings.v_sync_end   - timings.v_total

        super().__init__({
            "x": Out(signed(coord_width), reset=self.h_reset),
            "y": Out(signed(coord_width), reset=self.v_reset),
            "hsync": Out(unsigned(1)),
            "vsync": Out(unsigned(1)),
            "de": Out(unsigned(1)),
        })

    def elaborate(self, platform) -> Module:
        m = Module()

        timings = self.timings

        with m.If(self.x == (timings.h_active-1)):
            m.d.sync += self.x.eq(self.h_reset)
            with m.If(self.y == (timings.v_active-1)):
                m.d.sync += self.y.eq(self.v_reset)
            with m.Else():
                m.d.sync += self.y.eq(self.y+1)
        with m.Else():
            m.d.sync += self.x.eq(self.x+1)

        # Note: sync inversion is not here and must be handled before the PHY.
        m.d.comb += [
            self.hsync.eq((self.x >= self.hs_start) & (self.x < self.hs_end)),
            self.vsync.eq((self.y > self.vs_start) &
                          (self.y < self.vs_end) |
                          ((self.y == self.vs_start) & (self.x >= self.hs_start)) |
                          ((self.y == self.vs_end)   & (self.x < self.hs_start))),
            self.de.eq((self.x >= 0) & (self.y >= 0)),

        ]

        return m


class FramebufferPHY(wiring.Component):

    """
    Read pixels from a framebuffer in PSRAM and send them to the display.
    Pixels are DMA'd from PSRAM as a wishbone master in bursts of 'fifo_depth // 2' in the 'sync' clock domain.
    They are then piped with DVI timings to the display in the 'dvi' clock domain.

    Pixel storage itself is 8-bits: 4-bit intensity, 4-bit color.
    """

    def __init__(self, *, dvi_timings: DVITimings, fb_base, bus_master,
                 fb_size, fifo_depth=1024, fb_bytes_per_pixel=1):

        self.fifo_depth = fifo_depth
        self.fb_base = fb_base
        self.fb_hsize, self.fb_vsize = fb_size
        self.fb_bytes_per_pixel = fb_bytes_per_pixel

        # We are a DMA master
        self.bus = wishbone.Interface(addr_width=bus_master.addr_width, data_width=32, granularity=8,
                                      features={"cti", "bte"})

        # FIFO to cache pixels from PSRAM.
        self.fifo = AsyncFIFOBuffered(width=32, depth=fifo_depth, r_domain='dvi', w_domain='sync')

        # Kick this to start the core
        self.enable = Signal(1, reset=0)

        # Tracking in DVI domain
        self.dvi_tgen = DomainRenamer("dvi")(DVITimingGenerator(dvi_timings))
        self.bytecounter = Signal(exact_log2(4//self.fb_bytes_per_pixel))
        self.last_word   = Signal(32)
        self.consume_started = Signal(1, reset=0)

        # Current pixel color in DVI domain
        self.phy_r = Signal(8)
        self.phy_g = Signal(8)
        self.phy_b = Signal(8)

        # Color palette tweaking interface
        super().__init__({
            "palette_rgb": In(stream.Signature(data.StructLayout({
                "position": unsigned(8),
                "red":      unsigned(8),
                "green":    unsigned(8),
                "blue":     unsigned(8),
                }))),
        })

    @staticmethod
    def compute_color_palette():

        # Calculate 16*16 (256) color palette to map each 8-bit pixel storage
        # into R8/G8/B8 pixel value for sending to the DVI PHY. Each pixel
        # is stored as a 4-bit intensity and 4-bit color.
        #
        # TODO: make this runtime customizable?

        n_i = 16
        n_c = 16
        rs, gs, bs = [], [], []
        for i in range(n_i):
            for c in range(n_c):
                r, g, b = colorsys.hls_to_rgb(
                        float(c)/n_c, float(1.35**(i+1))/(1.35**n_i), 0.75)
                rs.append(int(r*255))
                gs.append(int(g*255))
                bs.append(int(b*255))

        return rs, gs, bs

    def elaborate(self, platform) -> Module:
        m = Module()

        m.submodules.fifo = self.fifo
        m.submodules.dvi_tgen = dvi_tgen = self.dvi_tgen

        # 'dvi' domain
        phy_r = self.phy_r
        phy_g = self.phy_g
        phy_b = self.phy_b

        # Create a VSync signal in the 'sync' domain.
        # NOTE: this is the same regardless of sync inversion.
        phy_vsync_sync = Signal()
        m.submodules.vsync_ff = FFSynchronizer(
                i=dvi_tgen.vsync, o=phy_vsync_sync, o_domain="sync")

        if sim.is_hw(platform):

            # DVI PHY (not needed for simulation).

            def add_sv(f):
                path = os.path.join("src/vendor/dvi", f)
                platform.add_file(f"build/{f}", open(path))

            add_sv("tmds_encoder_dvi.sv")
            add_sv("dvi_generator.sv")

            dvi_pins = platform.request("dvi")

            # Register all DVI timing signals to cut timing path.
            s_dvi_de = Signal()
            s_dvi_b = Signal(unsigned(8))
            s_dvi_g = Signal(unsigned(8))
            s_dvi_r = Signal(unsigned(8))
            m.d.dvi += [
                s_dvi_de.eq(dvi_tgen.de),
                s_dvi_r.eq(phy_r),
                s_dvi_g.eq(phy_g),
                s_dvi_b.eq(phy_b),
            ]

            # Sync inversion before sending to PHY if required.
            # Better here than in DVITimingsGenerator itself in case
            # the sync signal is used by other logic.

            s_dvi_hsync = Signal()
            if dvi_tgen.timings.h_sync_invert:
                m.d.dvi += s_dvi_hsync.eq(~dvi_tgen.hsync),
            else:
                m.d.dvi += s_dvi_hsync.eq(dvi_tgen.hsync),

            s_dvi_vsync = Signal()
            if dvi_tgen.timings.v_sync_invert:
                m.d.dvi += s_dvi_vsync.eq(~dvi_tgen.vsync),
            else:
                m.d.dvi += s_dvi_vsync.eq(dvi_tgen.vsync),

            # Instantiate the DVI PHY itself
            # TODO: port this to Amaranth as well!
            m.submodules.dvi_gen = Instance("dvi_generator",
                i_rst_pix = ResetSignal("dvi"),
                i_clk_pix = ClockSignal("dvi"),
                i_clk_pix_5x = ClockSignal("dvi5x"),

                i_de = s_dvi_de,
                i_data_in_ch0 = s_dvi_b,
                i_data_in_ch1 = s_dvi_g,
                i_data_in_ch2 = s_dvi_r,
                i_ctrl_in_ch0 = Cat(s_dvi_hsync, s_dvi_vsync),
                i_ctrl_in_ch1 = 0,
                i_ctrl_in_ch2 = 0,

                o_tmds_clk_serial = dvi_pins.ck.o,
                o_tmds_ch0_serial = dvi_pins.d0.o,
                o_tmds_ch1_serial = dvi_pins.d1.o,
                o_tmds_ch2_serial = dvi_pins.d2.o,
            )

        # DMA master bus
        bus = self.bus

        # Current offset into the framebuffer
        dma_addr = Signal(32)

        # Length of framebuffer in 32-bit words
        fb_len_words = (self.fb_bytes_per_pixel * (self.fb_hsize*self.fb_vsize)) // 4

        # DMA bus master -> FIFO state machine
        # Burst until FIFO is full, then wait until half empty.

        # Signal from 'dvi' to 'sync' domain to drain FIFO if we are in vsync.
        drain_fifo = Signal(1, reset=0)
        drain_fifo_dvi = Signal(1, reset=0)
        m.submodules.drain_fifo_ff = FFSynchronizer(
                i=drain_fifo, o=drain_fifo_dvi, o_domain="dvi")
        drained = Signal()

        # Read to FIFO in sync domain
        with m.FSM() as fsm:
            with m.State('OFF'):
                with m.If(self.enable):
                    m.next = 'BURST'
            with m.State('BURST'):
                m.d.comb += [
                    bus.stb.eq(1),
                    bus.cyc.eq(1),
                    bus.we.eq(0),
                    bus.sel.eq(2**(bus.data_width//8)-1),
                    bus.adr.eq(self.fb_base + dma_addr),
                    self.fifo.w_en.eq(bus.ack),
                    self.fifo.w_data.eq(bus.dat_r),
                    bus.cti.eq(
                        wishbone.CycleType.INCR_BURST),
                ]
                with m.If(self.fifo.w_level >= (self.fifo_depth-1)):
                    m.d.comb += bus.cti.eq(
                            wishbone.CycleType.END_OF_BURST)
                with m.If(bus.stb & bus.ack & self.fifo.w_rdy):
                    with m.If(dma_addr < (fb_len_words-1)):
                        m.d.sync += dma_addr.eq(dma_addr + 1)
                    with m.Else():
                        m.d.sync += dma_addr.eq(0)
                with m.Elif(~self.fifo.w_rdy):
                    m.next = 'WAIT'
            with m.State('WAIT'):
                with m.If(~phy_vsync_sync):
                    m.d.sync += drained.eq(0)
                with m.If(phy_vsync_sync & ~drained):
                    m.next = 'VSYNC'
                with m.Elif(self.fifo.w_level < self.fifo_depth//2):
                    m.next = 'BURST'
            with m.State('VSYNC'):
                # drain DVI side. We only want to drain once.
                m.d.comb += drain_fifo.eq(1)
                with m.If(self.fifo.w_level == 0):
                    m.d.sync += dma_addr.eq(0)
                    m.d.sync += drained.eq(1)
                    m.next = 'BURST'

        # 'dvi' domain: read FIFO -> DVI PHY (1 fifo word is N pixels)
        bytecounter = self.bytecounter
        last_word   = self.last_word
        with m.If(drain_fifo_dvi):
            m.d.dvi += bytecounter.eq(0)
            m.d.comb += self.fifo.r_en.eq(1),
        with m.Elif(dvi_tgen.de & self.fifo.r_rdy):
            m.d.comb += self.fifo.r_en.eq(bytecounter == 0),
            m.d.dvi += bytecounter.eq(bytecounter+1)
            with m.If(bytecounter == 0):
                m.d.dvi += last_word.eq(self.fifo.r_data)
            with m.Else():
                m.d.dvi += last_word.eq(last_word >> 8)

        rs, gs, bs = self.compute_color_palette()
        m.submodules.palette_r = palette_r = Memory(shape=unsigned(8), depth=256, init=rs)
        m.submodules.palette_g = palette_g = Memory(shape=unsigned(8), depth=256, init=gs)
        m.submodules.palette_b = palette_b = Memory(shape=unsigned(8), depth=256, init=bs)

        rd_port_r = palette_r.read_port(domain="comb")
        rd_port_g = palette_g.read_port(domain="comb")
        rd_port_b = palette_b.read_port(domain="comb")

        # Index by intensity (4-bit) and color (4-bit)
        m.d.comb += rd_port_r.addr.eq(Cat(last_word[0:4], last_word[4:8]))
        m.d.comb += rd_port_g.addr.eq(Cat(last_word[0:4], last_word[4:8]))
        m.d.comb += rd_port_b.addr.eq(Cat(last_word[0:4], last_word[4:8]))

        # hook up to DVI PHY
        m.d.comb += [
            phy_r.eq(rd_port_r.data),
            phy_g.eq(rd_port_g.data),
            phy_b.eq(rd_port_b.data),
        ]

        # palette write interface (p=position, rgb=value)
        wports = [palette_r.write_port(),
                  palette_g.write_port(),
                  palette_b.write_port()]
        # split rgb payload into one write for each rgb memory
        m.d.comb += [
            wports[0].data.eq(self.palette_rgb.payload.red),
            wports[1].data.eq(self.palette_rgb.payload.green),
            wports[2].data.eq(self.palette_rgb.payload.blue),
        ]
        m.d.comb += self.palette_rgb.ready.eq(1)
        # hook up position and stream valid -> write enable.
        for wport in wports:
            with m.If(self.palette_rgb.ready):
                m.d.comb += [
                    wport.addr.eq(self.palette_rgb.payload.position),
                    wport.en.eq(self.palette_rgb.valid),
                ]

        return m
