name: Build and publish Docker image

on:
  workflow_call:
  push:
    paths:
      - 'gateware/Dockerfile'
      - 'gateware/pyproject.toml'
      - 'gateware/pdm.lock'
      - '.github/workflows/docker.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: gateware
          push: true
          tags: ghcr.io/apfaudio/tiliqua-builder:latest 